package com.example.busnotice.global.config;

import com.example.busnotice.domain.busStop.CityCode;
import com.example.busnotice.domain.busStop.CityCodeRepository;
import java.util.Arrays;
import java.util.List;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class DataLoaderConfig {

    @Bean
    public ApplicationRunner dataLoader(CityCodeRepository cityCodeRepository) {
        return args -> {
            // 도시 코드와 이름 리스트
            List<CityCode> cityCodes = Arrays.asList(
                new CityCode("11", "서울특별시"),
                new CityCode("12", "세종특별시"),
                new CityCode("21", "부산광역시"),
                new CityCode("22", "대구광역시"),
                new CityCode("23", "인천광역시"),
                new CityCode("24", "광주광역시"),
                new CityCode("25", "대전광역시"),
                new CityCode("25", "계룡시"),
                new CityCode("26", "울산광역시"),
                new CityCode("39", "제주도"),
                new CityCode("31010", "수원시"),
                new CityCode("31020", "성남시"),
                new CityCode("31030", "의정부시"),
                new CityCode("31040", "안양시"),
                new CityCode("31050", "부천시"),
                new CityCode("31060", "광명시"),
                new CityCode("31070", "평택시"),
                new CityCode("31080", "동두천시"),
                new CityCode("31090", "안산시"),
                new CityCode("31100", "고양시"),
                new CityCode("31110", "과천시"),
                new CityCode("31120", "구리시"),
                new CityCode("31130", "남양주시"),
                new CityCode("31140", "오산시"),
                new CityCode("31150", "시흥시"),
                new CityCode("31160", "군포시"),
                new CityCode("31170", "의왕시"),
                new CityCode("31180", "하남시"),
                new CityCode("31190", "용인시"),
                new CityCode("31200", "파주시"),
                new CityCode("31210", "이천시"),
                new CityCode("31220", "안성시"),
                new CityCode("31230", "김포시"),
                new CityCode("31240", "화성시"),
                new CityCode("31250", "광주시"),
                new CityCode("31260", "양주시"),
                new CityCode("31270", "포천시"),
                new CityCode("31320", "여주시"),
                new CityCode("31350", "연천군"),
                new CityCode("31370", "가평군"),
                new CityCode("31380", "양평군"),
                new CityCode("32010", "춘천시"),
                new CityCode("32020", "원주시"),
                new CityCode("32020", "횡성군"),
                new CityCode("32050", "태백시"),
                new CityCode("32310", "홍천군"),
                new CityCode("32360", "철원군"),
                new CityCode("32410", "양양군"),
                new CityCode("33010", "청주시"),
                new CityCode("33020", "충주시"),
                new CityCode("33030", "제천시"),
                new CityCode("33320", "보은군"),
                new CityCode("33330", "옥천군"),
                new CityCode("33340", "영동군"),
                new CityCode("33350", "진천군"),
                new CityCode("33360", "괴산군"),
                new CityCode("33370", "음성군"),
                new CityCode("33380", "단양군"),
                new CityCode("34010", "천안시"),
                new CityCode("34020", "공주시"),
                new CityCode("34040", "아산시"),
                new CityCode("34050", "서산시"),
                new CityCode("34060", "논산시"),
                new CityCode("34070", "계룡시"),
                new CityCode("34330", "부여군"),
                new CityCode("34390", "당진시"),
                new CityCode("35010", "전주시"),
                new CityCode("35020", "군산시"),
                new CityCode("35040", "정읍시"),
                new CityCode("35050", "남원시"),
                new CityCode("35060", "김제시"),
                new CityCode("35320", "진안군"),
                new CityCode("35330", "무주군"),
                new CityCode("35340", "장수군"),
                new CityCode("35350", "임실군"),
                new CityCode("35360", "순창군"),
                new CityCode("35370", "고창군"),
                new CityCode("35380", "부안군"),
                new CityCode("36010", "목포시"),
                new CityCode("36020", "여수시"),
                new CityCode("36030", "순천시"),
                new CityCode("36040", "나주시"),
                new CityCode("36060", "광양시"),
                new CityCode("36320", "곡성군"),
                new CityCode("36330", "구례군"),
                new CityCode("36350", "고흥군"),
                new CityCode("36380", "장흥군"),
                new CityCode("36400", "해남군"),
                new CityCode("36410", "영암군"),
                new CityCode("36420", "무안군"),
                new CityCode("36430", "함평군"),
                new CityCode("36450", "장성군"),
                new CityCode("36460", "완도군"),
                new CityCode("36470", "진도군"),
                new CityCode("36480", "신안군"),
                new CityCode("37010", "포항시"),
                new CityCode("37020", "경주시"),
                new CityCode("37030", "김천시"),
                new CityCode("37040", "안동시"),
                new CityCode("37050", "구미시"),
                new CityCode("37060", "영주시"),
                new CityCode("37070", "영천시"),
                new CityCode("37080", "상주시"),
                new CityCode("37090", "문경시"),
                new CityCode("37100", "경산시"),
                new CityCode("37320", "의성군"),
                new CityCode("37330", "청송군"),
                new CityCode("37340", "영양군"),
                new CityCode("37350", "영덕군"),
                new CityCode("37360", "청도군"),
                new CityCode("37370", "고령군"),
                new CityCode("37380", "성주군"),
                new CityCode("37390", "칠곡군"),
                new CityCode("37400", "예천군"),
                new CityCode("37410", "봉화군"),
                new CityCode("37420", "울진군"),
                new CityCode("37430", "울릉군"),
                new CityCode("38010", "창원시"),
                new CityCode("38030", "진주시"),
                new CityCode("38050", "통영시"),
                new CityCode("38060", "사천시"),
                new CityCode("38070", "김해시"),
                new CityCode("38080", "밀양시"),
                new CityCode("38090", "거제시"),
                new CityCode("38100", "양산시"),
                new CityCode("38310", "의령군"),
                new CityCode("38320", "함안군"),
                new CityCode("38330", "창녕군"),
                new CityCode("38340", "고성군"),
                new CityCode("38350", "남해군"),
                new CityCode("38360", "하동군"),
                new CityCode("38370", "산청군"),
                new CityCode("38380", "함양군"),
                new CityCode("38390", "거창군"),
                new CityCode("38400", "합천군")
            );

            // 중복 삽입 방지 및 저장
            cityCodes.forEach(cityCode -> {
                if (!cityCodeRepository.existsByCode(cityCode.getCode())) {
                    cityCodeRepository.save(cityCode);
                }
            });
        };
    }
}
